services:
  qa_automation_api:
    build:
      dockerfile: Dockerfile
    start:
      command: ""  # Không ghi đè CMD
    environment:
      PYTHON_VERSION: 3.10
      RENDER_ENV: production
      CACHE_PATH: /app/data/embedding_cache.pkl
      FAISS_INDEX_PATH: /app/data/qa_index.faiss
      MODEL_PATH: /app/data/phobert_base
      CHECKPOINT_PATH: /app/data/phobert_finetuned
      DB_PORT: 3306
      CA_PATH: /app/certs/isrgrootx1.pem
      DB_SSL_ENABLED: false
      SERVICE: api
    variables:
      DB_HOST: ${{MYSQLHOST}}
      DB_USER: ${{MYSQLUSER}}
      DB_PASSWORD: ${{MYSQLPASSWORD}}
      DB_NAME: ${{MYSQLDATABASE}}
      REDIS_URL: ${{REDIS_URL}}
      API_KEY: cf2c57043f614f62966722a999aa13df
      PORT: 8080  # Đặt cổng mặc định phù hợp với Railway
    volumes:
      - path: /app/data
        size: 5GB

  qa_automation_celery:
    build:
      dockerfile: Dockerfile
    start:
      command: ""  # Không ghi đè CMD
    environment:
      PYTHON_VERSION: 3.10
      RENDER_ENV: production
      CACHE_PATH: /app/data/embedding_cache.pkl
      FAISS_INDEX_PATH: /app/data/qa_index.faiss
      MODEL_PATH: /app/data/phobert_base
      CHECKPOINT_PATH: /app/data/phobert_finetuned
      DB_PORT: 3306
      CA_PATH: /app/certs/isrgrootx1.pem
      DB_SSL_ENABLED: false
      SERVICE: celery
    variables:
      DB_HOST: ${{MYSQLHOST}}
      DB_USER: ${{MYSQLUSER}}
      DB_PASSWORD: ${{MYSQLPASSWORD}}
      DB_NAME: ${{MYSQLDATABASE}}
      REDIS_URL: ${{REDIS_URL}}
      API_KEY: cf2c57043f614f62966722a999aa13df
      PORT: 8080  # Đặt cổng mặc định phù hợp với Railway
    volumes:
      - path: /app/data
        size: 5GB

databases:
  mysql:
    name: qa_automation_db
  redis:
    name: qa_automation_redis