services:
  qa-automation-api:
    build:
      command: pip install -r requirements.txt
    start:
      command: uvicorn main3:app --host 0.0.0.0 --port $PORT
    environment:
      PYTHON_VERSION: 3.10.7
      RENDER_ENV: production
      CACHE_PATH: /app/data/embedding_cache.pkl
      FAISS_INDEX_PATH: /app/data/qa_index.faiss
      MODEL_PATH: /app/data/phobert_base
      CHECKPOINT_PATH: /app/data/phobert_finetuned
      DB_PORT: 3306
      CA_PATH: /app/certs/isrgrootx1.pem
      DB_SSL_ENABLED: false
    variables:
      DB_HOST: $MYSQLHOST
      DB_USER: $MYSQLUSER
      DB_PASSWORD: $MYSQLPASSWORD
      DB_NAME: $MYSQLDATABASE
      REDIS_URL: $REDIS_URL
      API_KEY: cf2c57043f614f62966722a999aa13df
    volumes:
      - path: /app/data
        size: 1GB
  qa-automation-celery:
    build:
      command: pip install -r requirements.txt
    start:
      command: celery -A celery_config worker --pool=solo --concurrency=1 --loglevel=info
    environment:
      PYTHON_VERSION: 3.10.7
      RENDER_ENV: production
      CACHE_PATH: /app/data/embedding_cache.pkl
      FAISS_INDEX_PATH: /app/data/qa_index.faiss
      MODEL_PATH: /app/data/phobert_base
      CHECKPOINT_PATH: /app/data/phobert_finetuned
      DB_PORT: 3306
      CA_PATH: /app/certs/isrgrootx1.pem
      DB_SSL_ENABLED: false
    variables:
      DB_HOST: $MYSQLHOST
      DB_USER: $MYSQLUSER
      DB_PASSWORD: $MYSQLPASSWORD
      DB_NAME: $MYSQLDATABASE
      REDIS_URL: $REDIS_URL
      API_KEY: cf2c57043f614f62966722a999aa13df
    volumes:
      - path: /app/data
        size: 5GB
databases:
  mysql:
    name: qa-automation-db
  redis:
    name: qa-automation-redis
    # Force new build to clear cache